### ISSUE TITLE
Instrumenting Apache Kafka clients with OpenTelemetry

### ISSUE THREAD

**Issue by louisonsarlinmagnus** [open-telemetry/opentelemetry.io#2069]
Hello,

I was following [this blog post](https://opentelemetry.io/blog/2022/instrument-kafka-clients/#instrumenting-by-using-the-agent) and I'm facing this error `Empty JMX configuration`.

### What I'm trying to achieve ?

I am trying to auto instrument a Kafka producer written in Java using the `opentelemetry-javaagent.jar`

### What I've done ?

I have a Kafka producer sending messages packaged in a jar.
I have downloaded the `opentelemetry-javaagent.jar` and placed it next to the jar of my app.

### What happen ?

When I execute this command :
`java -javaagent:../opentelemetry-javaagent.jar -Dotel.service.name=myapp -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=none -jar target/myapp.jar`

I get : 
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2022-12-02 07:55:31:056 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.20.2
[otel.javaagent 2022-12-02 07:55:35:656 +0000] [main] INFO io.opentelemetry.javaagent.shaded.instrumentation.jmx.engine.JmxMetricInsight - Empty JMX configuration, no metrics will be collected for InstrumentationScope io.opentelemetry.jmx
Exception in thread "main" java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
        at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
        at java.base/java.util.Properties.put(Properties.java:1340)
        at com.mycompany.project.KafkaProducerFactory.configureProducer(KafkaProducerFactory.java:21)
        at com.mycompany.project.KafkaProducerFactory.buildKafkaProducer(KafkaProducerFactory.java:15)
        at com.mycompany.project.MyApp.main(MyApp.java:24)
```

I cannot found any information about the missing configuration.

Do you guys know how I can solve my problem ?

Thank you !

**Comment by louisonsarlinmagnus** [comment]
Hi, It is I again !

I figured out that my `opentelemetry-javaagent.jar` was missing a property : 
`OTEL_JMX_TARGET_SYSTEM=kafka-broker`

Sorry for the inconvenience
