### ISSUE TITLE
Getting started with python is failing

### ISSUE THREAD

**Issue by leandrodamascena** [open-telemetry/opentelemetry.io#2687]
**What needs to be changed?** 

The initial python example is failing metrics because the double quotes are missing.

**What is the name + path of the page that needs changed?**

Path: https://opentelemetry.io/docs/instrumentation/python/getting-started/#metrics
Page title: Getting Started (Python version)

**Additional context**: 

```sh
opentelemetry-instrument \
    --traces_exporter console \
    --metrics_exporter console \
    --logs_exporter console \
    flask run
Traceback (most recent call last):
  File "/tmp/datadog/.venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/flask/cli.py", line 1063, in main
    cli.main()
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/flask/cli.py", line 911, in run_command
    raise e from None
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/flask/cli.py", line 897, in run_command
    app = info.load_app()
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/flask/cli.py", line 312, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "/tmp/datadog/.venv/lib64/python3.10/site-packages/flask/cli.py", line 218, in locate_app
    __import__(module_name)
  File "/tmp/datadog/app.py", line 8, in <module>
    meter = metrics.get_meter(diceroller.meter)
NameError: name 'diceroller' is not defined
```

**Comment by chalin** [comment]
Closed by #2688
