### ISSUE TITLE
Add OpenTelemetry .NET instrumentation docs

### ISSUE THREAD

**Issue by theletterf** [open-telemetry/opentelemetry.io#3150]
@Kielek and I want to port the docs in https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/tree/main/docs to https://opentelemetry.io/docs/instrumentation/net/automatic/. 

We discussed this briefly with @svrnm. Some data points:

- Release would likely happen this month 
- We would have to redo the Getting started so that it focuses on automatic instrumentation
- Flow and IA should resemble that of other languages in the docs (for example, Node; see https://github.com/open-telemetry/opentelemetry.io/issues/2829)
- Ideally, we could use a standard demo app as an example (https://github.com/open-telemetry/opentelemetry.io/issues/2623)

I'd be happy to help with this!

**Comment by svrnm** [comment]
Thanks for raising this issue @theletterf & @Kielek. @open-telemetry/docs-approvers please take a look and comment as well.

A few additional thoughts:
* Java already has some subpages for [Automatic](https://opentelemetry.io/docs/instrumentation/java/automatic/), in a similar way pages about Configuration, Plugins, etc could live here
* Redoing the Getting Started with the Demo App is for me the biggest win to end-users. I think that some content of some pages could also be incorporated into that (e.g. log-trace-correlation, see the Java Getting Started which outputs some logs already)
* For some pages we need to discuss if they should be moved or remain in the opentelemetry-dotnet-instrumentation repository, i.e. "developing", "design" and other documents which have contributors as audience. 

As an independent side-note: If I look at Java & .NET, Python, ... automatic instrumentation there are some _things_ that are kind of the same thing but use different wording, e.g. Java has "extensions", .NET has "plugins" or environment variables to enable certain instrumentation libraries (`OTEL_DOTNET_AUTO_[TRACES|METRICS|LOGS]_INSTRUMENTATIONS_ENABLED` vs `OTEL_PYTHON_DJANGO_INSTRUMENT` vs `OTEL_INSTRUMENTATION_[NAME]_ENABLED`), etc. Although those are language specific, this is highly confusing to users with multi-language environments, so it would be good to create some consistency here as well

**Comment by theletterf** [comment]
I think we can close the issue now!

**Comment by junaid-git** [comment]
Hi, I followed your documentation to add auto instrumentation https://opentelemetry.io/docs/instrumentation/net/automatic/nuget-packages/

Executing this command  "instrument.cmd Adp.ProductStore.Client.exe" throws following issue.

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at OpenTelemetry.AutoInstrumentation.NativeMethods+Windows.AddInstrumentations(System.String, OpenTelemetry.AutoInstrumentation.NativeCallTargetDefinition[], Int32)
--------------------------------
   at OpenTelemetry.AutoInstrumentation.NativeMethods.AddInstrumentations(System.String, OpenTelemetry.AutoInstrumentation.NativeCallTargetDefinition[])
   at OpenTelemetry.AutoInstrumentation.Instrumentation.RegisterBytecodeInstrumentations(Payload)
   at OpenTelemetry.AutoInstrumentation.Instrumentation.Initialize()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at OpenTelemetry.AutoInstrumentation.Loader.Loader.TryLoadManagedAssembly()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..cctor()
   at OpenTelemetry.AutoInstrumentation.Loader.Loader..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean, Boolean)
   at System.Activator.CreateInstance(System.Type, Boolean, Boolean)
   at System.RuntimeType.CreateInstanceImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Activator.CreateInstance(System.Type, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Reflection.Assembly.CreateInstance(System.String, Boolean, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo, System.Object[])
   at System.Reflection.Assembly.CreateInstance(System.String)
   at StartupHook.Initialize()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.StartupHookProvider.CallStartupHook(StartupHookNameOrPath)
   at System.StartupHookProvider.ProcessStartupHooks()

**Comment by Kielek** [comment]
@junaid-git, lets discuss it under https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/3199
