### ISSUE TITLE
Python "Getting Started" demo does not work with Python 3.11

### ISSUE THREAD

**Issue by ekquasar** [open-telemetry/opentelemetry.io#3607]
From [the docs](https://github.com/open-telemetry/opentelemetry.io/blob/main/content/en/docs/instrumentation/python/getting-started.md), the code does not work as-is.

The string formatting on line 15 for the `app.py` fails with the following traceback upon `curl "localhost:8080/rolldice?player=foo"`:

Run server:
```
flask run --port 8080
```

After curl:
```
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:8080
INFO:werkzeug:Press CTRL+C to quit
--- Logging error ---
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 390, in handle
    super().handle()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/werkzeug/serving.py", line 323, in execute
    application_iter = app(environ, start_response)
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ekquasar_1/src/otel-demo/venv/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/ekquasar_1/src/otel-demo/app.py", line 15, in roll_dice
    logger.warn("{} is rolling the dice: {}", player, result)
Message: '{} is rolling the dice: {}'
Arguments: ('foo', '2')
```

**Comment by svrnm** [comment]
@ekquasar thanks for reporting, can you/could you verify that this is specific to python3.11?

**Comment by ekquasar** [comment]
How about just a PR?
https://github.com/open-telemetry/opentelemetry.io/pull/3609

**Comment by svrnm** [comment]
> How about just a PR? #3609
> 
> EDIT: Is there CI for the code examples? If not, do you have plans for them and how can I get involved there?

No CI for the code examples as of today. There are plans in our (=maintainers) heads, but nothing concrete. I may create an issue on that later and let you know

**Comment by ekquasar** [comment]
Linking: https://github.com/open-telemetry/opentelemetry.io/issues/3633

**Comment by ekquasar** [comment]
solved by adding `werkzeug<3` to the docs' Python requirements
