### ISSUE TITLE
Create documentation for running the OTel Demo on GitHub Codespaces

### ISSUE THREAD

**Issue by avillela** [open-telemetry/opentelemetry.io#4725]
I think that it would be helpful to the community to have documentation on running the OTel Demo using GitHub Codespaces. We can do it in one of two ways:
1. Blog post
2. Add it to the docs

Thoughts??

**Comment by svrnm** [comment]
thanks @avillela, as you know I always prefer more docs over having blog posts;-) but in that particular case I wonder more about GH codespaces being a commercial solution how well that goes with our social media guide. I _might_ be overly paranoid here, especially sing codespaces is not an o11y product, but I wanted to call that out. 

I would enjoy reading such a blog post (or docs page), but I am conflicted on that.

@open-telemetry/demo-approvers @open-telemetry/docs-approvers, wdyt?

**Comment by puckpuck** [comment]
I'm not even sure it works, but getting the otel-demo to work in a dev container environment and using GitHub Codespaces as an example in a blog post would be okay.

**Comment by avillela** [comment]
> I'm not even sure it works, but getting the otel-demo to work in a dev container environment and using GitHub Codespaces as an example in a blog post would be okay.

I did get it running a few weeks back in GH Codespaces - had to beef up the container specs to get it to work and have the various UIs run 😁

**Comment by julianocosta89** [comment]
I'd be okay with it, but as @svrnm mentioned, I believe we should try to keep it as agnostic as possible.
@avillela is there much config difference in running locally with `devcontainer` and GH Codespaces?

Mastodon project has the `.devcontainer` definition in its repo and when you open the project, you get a pop up asking if you'd like to open it in codespaces or locally.

The blog/doc could focus on running the demo locally, and if people want to run in Codespaces, they could use the same config, but we as community do not "advertise" it. WDYT?

**Comment by puckpuck** [comment]
+1 to getting a proper `.devcontainer` definition in the Otel demo so it can work in that world.

**Comment by svrnm** [comment]
Not an expert on the matter, but if there is an OSS solution under codespaces we could support _officially_ that would be my favourite solution.

**Comment by avillela** [comment]
I definitely dig the idea @julianocosta89. I can explore a pure devcontainer solution a bit further. Stay tuned!

**Comment by avillela** [comment]
Okay...I created a `devcontainer` that seems to work. Check it out [here](https://github.com/avillela/opentelemetry-demo/blob/avillela-add-devcontainer/.devcontainer/devcontainer.json). I'll submit a PR as well, to get the convo going.

**Comment by julianocosta89** [comment]
@avillela I've tried it on my M1 and got the following error:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: waiting for init preliminary setup: read init-p: connection reset by peer: unknown
```

Have you faced something similar?

**Comment by avillela** [comment]
> @avillela I've tried it on my M1 and got the following error:
> 
> ```
> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: waiting for init preliminary setup: read init-p: connection reset by peer: unknown
> ```
> 
> Have you faced something similar?

Do you get this error when starting up the devcontainer locally?

The issue I've had is that [ARM images aren't supported by devcontainers](https://stackoverflow.com/questions/66493499/how-to-get-arm-docker-images-when-creating-devcontainer-is-vs-code-mac-m1), so the workaround is to first pull the amd64 version of the image manually before trying to run the devcontainer:

```shell
docker pull --platform linux/amd64 mcr.microsoft.com/devcontainers/universal:dev-linux
```

**Comment by julianocosta89** [comment]
@avillela awesome!
I think the `"ghcr.io/devcontainers/features/docker-in-docker:2` was the missing piece ⭐ 

It works great!

QQ as we are at it, do we want to focus on the `devcontainer` just to run the demo, or could we also add the programming languages dependencies and use it to modify the services as well?
With that we could use the guide as a contributing guide too, WDYT?

**Comment by julianocosta89** [comment]
Doing some tests, I've just noticed that OpenSearch doesn't start 😢 

```
Disabling OpenSearch Security Plugin
Enabling execution of OPENSEARCH_HOME/bin/opensearch-performance-analyzer/performance-analyzer-agent-cli for OpenSearch Performance Analyzer Plugin
WARNING: Using incubator modules: jdk.incubator.vector
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/opensearch/lib/opensearch-2.14.0.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
WARNING: System::setSecurityManager will be removed in a future release
Jul 18, 2024 6:41:39 AM sun.util.locale.provider.LocaleProviderAdapter <clinit>
WARNING: COMPAT locale provider will be removed in a future release
[2024-07-18T06:41:40,178][WARN ][o.o.b.JNANatives         ] [demo-node] unable to install syscall filter: 
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
        at org.opensearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:375) ~[opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:666) ~[opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:281) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:128) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:129) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:191) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-2.14.0.jar:2.14.0]
        at org.opensearch.cli.Command.main(Command.java:101) [opensearch-cli-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138) [opensearch-2.14.0.jar:2.14.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104) [opensearch-2.14.0.jar:2.14.0]
./opensearch-docker-entrypoint.sh: line 69:    30 Killed                  "$@" "${opensearch_opts[@]}"
```

As it doesn't start, we do not get logs in Grafana.

**Comment by avillela** [comment]
Interesting. Have you tried re-strating services (`docker compose down` followed by `docker compose up`)? For example, I find sometimes that the Grafana UI doesn't load up initially, and I have to re-start and then it works. I suspect that the same thing may happen for OpenSearch. I only mention this because I just did a test both via local Dev Container and in GH Codespaces and logs are showing for me. Attaching screen shots of logs.

<img width="1510" alt="Screenshot 2024-07-18 at 10 31 22" src="https://github.com/user-attachments/assets/33ed4c7f-38c3-4e70-92ee-3a340d0e0d6e">

<img width="1506" alt="Screenshot 2024-07-18 at 10 29 11" src="https://github.com/user-attachments/assets/86221540-9bf7-472c-8e81-4ac4a7e81f74">

**Comment by avillela** [comment]
@julianocosta89 to answer your other question, we could definitely expand the Dev Container to enable development as well. It would certainly lower the barrier to contribution.

**Comment by avillela** [comment]
@julianocosta89 another thing to add...so I ran a bunch of tests today, and it does look like eventually I end up getting various IO errors which means that logs aren't always getting through. I spent a ton of time trying to search for a culprit but didn't have any luck. I think it may either be because the devcontainer specs aren't beefy enough (GH codespaces lets me have a max of 4 cores and 16GB RAM, and my own local Docker is restricted at 3 cores and 9GB RAM). Another possibility may be related to the fact that we're running Docker in Docker. Any thoughts?

**Comment by avillela** [comment]
Latest update. I have a new version of the dev container pushed. I based it off of the "Blank" image in GitHub Codespaces that I used for my original pre-devcontainer experiment. It basically includes additional features. I ran a couple of tests and I'm not seeing the weird timeouts that I was seeing before. It also incldues various language runtimes, so we could technically use it as a dev environment too.

**Comment by julianocosta89** [comment]
That looks great @avillela!

The OpenSearch issue is still ongoing though 😭 

Maybe we need to configure `CONFIG_SECCOMP`, but no idea what are the implications here 🤔

**Comment by avillela** [comment]
@julianocosta89 to confirm - the OpenSearch issue happens when running locally but not in Codespaces?

**Comment by julianocosta89** [comment]
@avillela I haven't tried in codespaces, just locally

**Comment by avillela** [comment]
@julianocosta89 I'd be curious to see what happens locally. Also, you're not seeing any logs on your end in Grafana then? I only ask because I don't see that error locally on my end. So very confused!

**Comment by julianocosta89** [comment]
@avillela maybe it is an issue on Mac 🙃 

In which OS are you running the demo?

**Comment by avillela** [comment]
> @avillela maybe it is an issue on Mac 🙃
> 
> In which OS are you running the demo?

I'm running MacOS Sonoma 14.5, and Docker 24.0.2

**Comment by julianocosta89** [comment]
I'm on Docker version: 24.0.7
MacOS Sonoma 14.5

🙃

**Comment by avillela** [comment]
One more question - what resources did you dedicate to Docker? I allocated 3 CPUs and 9GB RAM. And are you running anything else in Docker at the same time? It's a beefy image. 🙃

**Comment by julianocosta89** [comment]
> One more question - what resources did you dedicate to Docker? I allocated 3 CPUs and 9GB RAM. And are you running anything else in Docker at the same time? It's a beefy image. 🙃

Nope, just testing the devcontainer and starting the demo ofc.

I have 10 CPUs and 32GB RAM allocated for Docker, what is extremely high 😅

**Comment by avillela** [comment]
I'm out of ideas. I'm so confused. Can you try to run it remotely in GH Codespaces? Just curious to see what happens.

**Comment by avillela** [comment]
Also, would you be open to pairing on this? I'm out until July 12th, so sometime that week?

**Comment by avillela** [comment]
One other thing that came to mind. Have to tried clearing all of your existing Docker images and volumes to make sure that nothing has been cached?

**Comment by julianocosta89** [comment]
@avillela I'll try the codespaces later this week.
And I'd be up to pairing in this one, I'd love to have that working.

When you are back, I'll be out 🙃 
I'll be back on the August 26th.

**Comment by avillela** [comment]
> @avillela I'll try the codespaces later this week. And I'd be up to pairing in this one, I'd love to have that working.
> 
> When you are back, I'll be out 🙃 I'll be back on the August 26th.

Ping me when you get back and we'll set something up!

**Comment by julianocosta89** [comment]
@avillela I've tested the devcontainer today and it worked! 🥳

**Comment by julianocosta89** [comment]
for some reason `flagd` didn't start automatically, but `docker compose up flagd -d` solved.

Another thing that I'm noticing is that for some reason `accountingservice` is not sending traces 🤔

**Comment by avillela** [comment]
Out of curiosity, is this when running the dev container locally or in GH Codespaces?

**Comment by julianocosta89** [comment]
> Out of curiosity, is this when running the dev container locally or in GH Codespaces?

devcontainer locally
