### ISSUE TITLE
Markdownlint checking fails with upgrade to 0.37.x

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry.io#5767]
Upgrading `markdownlint ` to `0.37.0` causes the following error:

```console
$ npm run check:markdown
...

(node:7278) ExperimentalWarning: CommonJS module /Users/chalin/git/lf/open-telemetry/opentelemetry.io/gulp-src/lint-md.js is loading ES Module /Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/markdownlint/lib/exports.mjs using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[18:43:38] Using gulpfile ~/git/lf/open-telemetry/opentelemetry.io/gulpfile.js
[18:43:38] Starting 'lint-md'...
[18:43:38] 'lint-md' errored after 25 ms
[18:43:38] TypeError: markdownlint is not a function
    at Transform.markdownLintFile [as _transform] (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/gulp-src/lint-md.js:45:3)
    at Transform._read (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at Transform._write (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:155:83)
    at doWrite (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:390:139)
    at writeOrBuffer (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:381:5)
    at Writable.write (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:11)
    at Transform.ondata (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:629:20)
    at Transform.emit (node:events:524:28)
    at Transform.emit (node:domain:552:15)
    at addChunk (/Users/chalin/git/lf/open-telemetry/opentelemetry.io/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:279:12)
```

**Comment by chalin** [comment]
@trask @dyladan @svrnm - any idea, off the top, of how to most easily/quickly fix this. I haven't investigated yet, but have a hunch (and a hope) that it shouldn't be too hard to fix 🤞

**Comment by trask** [comment]
looks related to the recent changes in https://github.com/DavidAnson/markdownlint/blob/main/example/gulpfile.cjs

**Comment by trask** [comment]
in case it helps in this repo: https://github.com/open-telemetry/semantic-conventions/pull/1706

**Comment by chalin** [comment]
Thanks @trask. I'm tempted to dump the Gulp task too, but this repo has a custom linter rule, and I'm not sure how easy it would be to integrate it otherwise. I'll sit on this a bit more.
